package com.shettyharshith33.placementpro.utils

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.os.Environment
import android.widget.Toast
import com.shettyharshith33.placementpro.models.User
import java.io.File
import java.io.FileOutputStream

object ResumeGenerator {

    fun generateResumePdf(context: Context, user: User) {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 Size
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas
        val paint = Paint()

        // --- Title / Header ---
        paint.textAlign = Paint.Align.CENTER
        paint.textSize = 24f
        paint.isFakeBoldText = true
        canvas.drawText("PLACEMENT PRO - RESUME", 297f, 50f, paint)

        paint.textSize = 18f
        paint.color = Color.DKGRAY
        canvas.drawText(user.name.uppercase(), 297f, 80f, paint)

        // --- Standard Info Area ---
        paint.textAlign = Paint.Align.LEFT
        paint.textSize = 12f
        paint.color = Color.BLACK
        paint.isFakeBoldText = false

        var yPos = 130f
        val lineSpacing = 25f

        canvas.drawText("Email: ${user.email}", 50f, yPos, paint)
        yPos += lineSpacing
        canvas.drawText("Branch: ${user.branch}", 50f, yPos, paint)
        yPos += lineSpacing
        canvas.drawText("CGPA: ${user.cgpa}", 50f, yPos, paint)
        yPos += lineSpacing
        canvas.drawText("Backlogs: ${user.backlogs}", 50f, yPos, paint)
        
        yPos += 40f
        paint.textSize = 16f
        paint.isFakeBoldText = true
        canvas.drawText("PROFESSIONAL SUMMARY", 50f, yPos, paint)
        
        yPos += 20f
        paint.textSize = 12f
        paint.isFakeBoldText = false
        val summary = "Aspiring professional with a focus on ${user.branch}. Committed to excellence and continuous learning in the field of technology and placements."
        canvas.drawText(summary, 50f, yPos, paint)

        // --- Branding Footnote ---
        paint.textSize = 10f
        paint.color = Color.GRAY
        paint.textAlign = Paint.Align.CENTER
        canvas.drawText("Generated by PlacementPro Dashboard", 297f, 800f, paint)

        pdfDocument.finishPage(page)

        val file = File(context.getExternalFilesDir(null), "${user.name.replace(" ", "_")}_Resume.pdf")

        try {
            pdfDocument.writeTo(FileOutputStream(file))
            Toast.makeText(context, "Resume PDF Generated: ${file.absolutePath}", Toast.LENGTH_LONG).show()
        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(context, "Error generating PDF", Toast.LENGTH_SHORT).show()
        }

        pdfDocument.close()
    }
}
